version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: filter-db-postgres
    environment:
      POSTGRES_DB: filter-db
      POSTGRES_USER: psuser
      POSTGRES_PASSWORD: pspass
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psuser -d filter-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
